### ISSUE TITLE
Broken hotel list for 2020 Conference

### ISSUE THREAD

**Issue by astroshima** [ESUG/esug.github.io#122]
Hello,
there is broken list of hotels here:
https://esug.github.io/2020-Conference/conf2020.html
I live in Novi Sad city so I know that the list is broken. The list breaks after "Leopold I" hotel.
My web browser is: Firefox 72.0.1 (64-bit).
OS: Ubuntu 19.10 (64-bit).

Here is a screenshot with this issue from my web browser:

![Broken_hotel_list_2020-01-25 23-36-17](https://user-images.githubusercontent.com/42306523/73128338-09e46f80-3fce-11ea-9ba2-93c5c46be762.png)

**Comment by astroshima** [comment]
Hi,
 I am just an amateur "programmer" but I guess that the cause of the problem is plus sign ("+") in the hotel list in the line 129:
 "- *Leopold I>http://www.leopoldns.com/*, 25 minutes **+** stairs to the fortress"
 in this source file:
 "esug.github.io/2020-Conference/conf2020.pillar"
 https://github.com/ESUG/esug.github.io/blob/source/2020-Conference/conf2020.pillar
 Sorry if I am wrong about this.

**Comment by MarcusDenker** [comment]
Indeed, the + was the problem. I committed a fix!
