### ISSUE TITLE
Website does not build and deploy

### ISSUE THREAD

**Issue by gocko** [ESUG/esug.github.io#194]
I was adding more details to the IWST CFP (PC, submission page,...) but it does not build. Multiple-checked the syntax, and finally retired to build previous commits that were passing all checks - not passing.
Problem:
"Project: Citezen 2.6
...RETRY->ConfigurationOfSmaCC
...RETRY->ConfigurationOfSmaCCConnectionClosed: Connection closed while waiting for data.
"

**Comment by MarcusDenker** [comment]
this was fixed
