### ISSUE TITLE
Multiple links broken in 2023 page

### ISSUE THREAD

**Issue by hernanmd** [ESUG/esug.github.io#310]
On the https://esug.org/2023-Conference/conf2023.html page, multiple links return "Page not found":

- Slides link , the **slides** link should point to the slides found in https://github.com/ESUG/esug.github.io/tree/source/2023-Conference/slides
- The Conference Program, which points to https://esug.github.io/2023-Conference/agenda/agenda.html, is broken.
- The  Call for Paper: IWST23 CFP is also broken: https://esug.org/2023-Conference/cfpIWST2023.html
- And PDF Archive: http://www.esug.org/data/ESUG2023/

**Comment by MarcusDenker** [comment]
Fixed !
