### ISSUE TITLE
Multiple problems with the ESUG 2024 conference page(s)

### ISSUE THREAD

**Issue by JoachimTuchel** [ESUG/esug.github.io#311]
There are multiple problems with the 2024 conference page:

* The link from the conference program to the abstracts leads to a 404 page
* The HelloAsso Link on the conference page points to the ESUG-2023 page, so you cannot pay for the conference
* The "Conferences" dropdown misses the 2024 conference
* The backgorund image of the registration site is extremely big and loads slowly (and it seems to be an image of Lyon)

This all makes a bit of an unprofessional impression and may not be very helpful in attracting not-yet-members of the Smalltalk community.

**Comment by MarcusDenker** [comment]
The link from the conference program to the abstracts leads to a 404 page
	this seems to be already fixed

The HelloAsso Link on the conference page points to the ESUG-2023 page, so you cannot pay for the conference
	fixed


The "Conferences" dropdown misses the 2024 conference
	fixed


The backgorund image of the registration site is extremely big and loads slowly (and it seems to be an image of Lyon)
       I will open an issue dedicated to this
